[package]
name = "rcc"
version = "0.1.0"
authors = ["Daniel Spencer <dms305@hku.hk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
regex = "1"
tempfile = "3"
